### PR TITLE
Add instructions on how to submit expense reimbursements

### PR DESCRIPTION
**Pull request by talsafran**

### CODE REVIEW

**Comment by chawang90** [comment]
@Tal there's a typo in your listed instructions - should be $25 or more, not $50 or more for receipt. Otherwise looks great, thanks.

**Comment by chawang90** [comment]
@talsafran technically I think this should go into the employee wiki, not the handbook but just a nitpick, nothing essential. The handbook should be the backbone of our policies, whereas the granular "here's how you do x and y" can go into the employee wiki.

**Comment by talsafran** [comment]
No that's totally valid.

On Wed, Feb 24, 2016 at 11:57 PM, Charley Wang notifications@github.com
wrote:

> @talsafran https://github.com/talsafran technically I think this should
> go into the employee wiki, not the handbook but just a nitpick, nothing
> essential. The handbook should be the backbone of our policies, whereas the
> granular "here's how you do x and y" can go into the employee wiki.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/josephine/handbook/pull/39#issuecomment-188659122.

## 

cto // co-founder
josephine.com // @talsafran http://twitter.com/talsafran

**Comment by talsafran** [comment]
I can `git revert` that commit :)

On Thu, Feb 25, 2016 at 10:59 AM, Tal Safran tal@josephine.com wrote:

> No that's totally valid.
> 
> On Wed, Feb 24, 2016 at 11:57 PM, Charley Wang notifications@github.com
> wrote:
> 
> > @talsafran https://github.com/talsafran technically I think this
> > should go into the employee wiki, not the handbook but just a nitpick,
> > nothing essential. The handbook should be the backbone of our policies,
> > whereas the granular "here's how you do x and y" can go into the employee
> > wiki.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/josephine/handbook/pull/39#issuecomment-188659122.
> 
> ## 
> 
> cto // co-founder
> josephine.com // @talsafran http://twitter.com/talsafran

## 

cto // co-founder
josephine.com // @talsafran http://twitter.com/talsafran

**Pull request merged**
